/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-08-14 13:23:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.console;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<title>BABASPORT Administrator's Control Panel - powered by babasport</title>\r\n");
      out.write("<link href=\"/css/admin.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/theme.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/jquery.validate.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/jquery.treeview.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/jquery.ui.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/jquery.ext.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/jquery.form.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/itcast.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/admin.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style type=\"text/css\">        \r\n");
      out.write("*{margin:0;padding:0}\r\n");
      out.write("a:focus {outline:none;}\r\n");
      out.write("html{height:100%;overflow:hidden;}\r\n");
      out.write("body{height:100%;}\r\n");
      out.write("#top{ background-color:#1d63c6; height:69px; width:100%;}\r\n");
      out.write(".logo{width:215px; height:69px;}\r\n");
      out.write(".topbg{background:url(/images/admin/top-tbg.png) no-repeat; height:38px;}\r\n");
      out.write(".login-welcome{padding-left:20px; color:#fff; font-size:12px;background:url(/images/admin/topbg.gif) no-repeat;}\r\n");
      out.write(".login-welcome a:link,.login-welcome a:visited{color:#fff; text-decoration:none;}\r\n");
      out.write("\r\n");
      out.write("#welcome {color: #FFFFFF;padding: 0 30px 0 5px;}\r\n");
      out.write("#logout {color: #FFFFFF; padding-left: 5px;}\r\n");
      out.write("\r\n");
      out.write(".nav{height:31px; overflow:hidden;}\r\n");
      out.write(".nav-menu{background:url(/images/admin/bg.png) repeat-x; height:31px; list-style:none; padding-left:20px; font-size:14px;}\r\n");
      out.write(".nav .current {background: url(/images/admin/navcurrbg.gif) no-repeat 0px 2px; color:#fff; width:72px; text-align:center;} \r\n");
      out.write(".nav .current a{color:#fff;}\r\n");
      out.write(".nav-menu li {height:31px;text-align:center; line-height:31px; float:left; }\r\n");
      out.write(".nav-menu li a{color:#2b2b2b; font-weight:bold;}\r\n");
      out.write(".nav-menu li.sep{background: url(/images/admin/step.png) no-repeat; width:2px; height:31px; margin:0px 5px;}\r\n");
      out.write(".nav .normal{width:72px; text-align:center;}\r\n");
      out.write(".top-bottom{width:100%; background: url(/images/admin/bg.png) repeat-x 0px -34px; height:3px;}\r\n");
      out.write(".undis{display:none;}\r\n");
      out.write(".dis{display:block;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function HoverLi(id){\r\n");
      out.write("\t$(\"li[id^='tb_']\").each(function(){\r\n");
      out.write("\t\t$(this).removeClass(\"current\");\r\n");
      out.write("\t\t$(this).addClass(\"normal\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#tb_\"+id).removeClass(\"normal\");\r\n");
      out.write("\t$(\"#tb_\"+id).addClass(\"current\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"top\">\r\n");
      out.write("     <div class=\"top\">\r\n");
      out.write("          <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"215\"><div class=\"logo\"><img src=\"/images/admin/logo.jpg\" width=\"215\" height=\"69\" /></div></td>\r\n");
      out.write("            <td valign=\"top\">\r\n");
      out.write("                <div class=\"topbg\">\r\n");
      out.write("                     <div class=\"login-welcome\">\r\n");
      out.write("                             <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                                  <tr>\r\n");
      out.write("                                    <td width=\"420\" height=\"38\">\r\n");
      out.write("                                    <img src=\"/images/admin/welconlogin-icon.png\"/><span id=\"welcome\">您好:admin!</span>\r\n");
      out.write("                                    <img src=\"/images/admin/loginout-icon.png\"/><a href=\"logout.do?returnUrl=index.do\" target=\"_top\" id=\"logout\" onclick=\"return confirm('您确定退出吗?');\">退出</a> \r\n");
      out.write("                                    <img src=\"/images/admin/message-unread.png\"/>&nbsp;<a href=\"message/v_list.do\" target=\"rightFrame\">你有<span id=\"countDiv\">0</span>条信息未读</a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                  </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                       </div>  \r\n");
      out.write("                     <div class=\"nav\">\r\n");
      out.write("                     \t  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <td style=\"background-image:url('/images/admin/nav-left.png')\" width=\"14\" height=\"31\"></td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                \t<ul class=\"nav-menu\">\r\n");
      out.write("                                    \t<li class=\"current\" id=\"tb_11\" onclick=\"HoverLi(11);\"><a href=\"main.do\" target=\"mainFrame\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_12\" onclick=\"HoverLi(12);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">商品</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_13\" onclick=\"HoverLi(13);\"><a href=\"frame/order_main.do\" target=\"mainFrame\">订单</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_14\" onclick=\"HoverLi(14);\"><a href=\"frame/ad_main.do\" target=\"mainFrame\">广告</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_15\" onclick=\"HoverLi(15);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">支付</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_16\" onclick=\"HoverLi(16);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">资源</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_17\" onclick=\"HoverLi(17);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">辅助</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_18\" onclick=\"HoverLi(18);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">维护</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_19\" onclick=\"HoverLi(19);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">生成</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_20\" onclick=\"HoverLi(20);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">用户</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"sep\"></li><li class=\"normal\" id=\"tb_21\" onclick=\"HoverLi(21);\"><a href=\"frame/product_main.do\" target=\"mainFrame\">配置</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                     </div>  \r\n");
      out.write("                </div>\r\n");
      out.write("                </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("     </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top-bottom\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
