/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2017-08-14 13:27:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.console.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/console/product/../head.jsp", Long.valueOf(1502715305494L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<link href=\"/css/admin.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/theme.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/jquery.validate.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/jquery.treeview.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"/css/jquery.ui.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/kindeditor-4.1.10/kindeditor-all-min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/kindeditor-4.1.10/lang/zh_CN.js\"></script>\r\n");
      out.write("<script src=\"/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/jquery.ext.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/jquery.form.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/itcast.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/admin.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<title>babasport-list</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//上架\r\n");
      out.write("function isShow(){\r\n");
      out.write("\t//请至少选择一个\r\n");
      out.write("\tvar size = $(\"input[name='ids']:checked\").size();\r\n");
      out.write("\tif(size == 0){\r\n");
      out.write("\t\talert(\"请至少选择一个\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t//你确定删除吗\r\n");
      out.write("\tif(!confirm(\"你确定上架吗\")){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t//提交 Form表单\r\n");
      out.write("\t$(\"#jvForm\").attr(\"action\",\"/brand/isShow.do\");\r\n");
      out.write("\t$(\"#jvForm\").attr(\"method\",\"post\");\r\n");
      out.write("\t$(\"#jvForm\").submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"box-positon\">\r\n");
      out.write("\t<div class=\"rpos\">当前位置: 商品管理 - 列表</div>\r\n");
      out.write("\t<form class=\"ropt\">\r\n");
      out.write("\t\t<input class=\"add\" type=\"button\" value=\"添加\" onclick=\"window.location.href='add.jsp'\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"body-box\">\r\n");
      out.write("<form action=\"/product/list.do\" method=\"post\" style=\"padding-top:5px;\">\r\n");
      out.write("名称: <input type=\"text\" name=\"name\"/>\r\n");
      out.write("\t<select name=\"brandId\">\r\n");
      out.write("\t\t<option value=\"\">请选择品牌</option>\r\n");
      out.write("\t\t<option value=\"1\">依琦莲</option>\r\n");
      out.write("\t\t<option value=\"2\">凯速（KANSOON）</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<select name=\"isShow\">\r\n");
      out.write("\t\t<option value=\"1\">上架</option>\r\n");
      out.write("\t\t<option selected=\"selected\" value=\"0\">下架</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<input type=\"submit\" class=\"query\" value=\"查询\"/>\r\n");
      out.write("</form>\r\n");
      out.write("<form id=\"jvForm\">\r\n");
      out.write("<table cellspacing=\"1\" cellpadding=\"0\" width=\"100%\" border=\"0\" class=\"pn-ltable\">\r\n");
      out.write("\t<thead class=\"pn-lthead\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th width=\"20\"><input type=\"checkbox\" onclick=\"Pn.checkbox('ids',this.checked)\"/></th>\r\n");
      out.write("\t\t\t<th>商品编号</th>\r\n");
      out.write("\t\t\t<th>商品名称</th>\r\n");
      out.write("\t\t\t<th>图片</th>\r\n");
      out.write("\t\t\t<th width=\"4%\">新品</th>\r\n");
      out.write("\t\t\t<th width=\"4%\">热卖</th>\r\n");
      out.write("\t\t\t<th width=\"4%\">推荐</th>\r\n");
      out.write("\t\t\t<th width=\"4%\">上下架</th>\r\n");
      out.write("\t\t\t<th width=\"12%\">操作选项</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</thead>\r\n");
      out.write("\t<tbody class=\"pn-ltbody\">\r\n");
      out.write("\t\t<tr bgcolor=\"#ffffff\" onmouseover=\"this.bgColor='#eeeeee'\" onmouseout=\"this.bgColor='#ffffff'\">\r\n");
      out.write("\t\t\t<td><input type=\"checkbox\" name=\"ids\" value=\"73\"/></td>\r\n");
      out.write("\t\t\t<td>20141028114510003</td>\r\n");
      out.write("\t\t\t<td align=\"center\">依琦莲2014瑜伽服套装新款 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><img width=\"50\" height=\"50\" src=\"/images/pic/ppp.jpg\"/></td>\r\n");
      out.write("\t\t\t<td align=\"center\">是</td>\r\n");
      out.write("\t\t\t<td align=\"center\">是</td>\r\n");
      out.write("\t\t\t<td align=\"center\">是</td>\r\n");
      out.write("\t\t\t<td align=\"center\">下架</td>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"pn-opt\">查看</a> | <a href=\"#\" class=\"pn-opt\">修改</a> | <a href=\"#\" onclick=\"if(!confirm('您确定删除吗？')) {return false;}\" class=\"pn-opt\">删除</a> | <a href=\"../sku/list.jsp\" class=\"pn-opt\">库存</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"#ffffff\" onmouseover=\"this.bgColor='#eeeeee'\" onmouseout=\"this.bgColor='#ffffff'\">\r\n");
      out.write("\t\t\t<td><input type=\"checkbox\" name=\"ids\" value=\"73\"/></td>\r\n");
      out.write("\t\t\t<td>20141028114411609</td>\r\n");
      out.write("\t\t\t<td align=\"center\">依琦莲2014瑜伽服套装新款 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><img width=\"50\" height=\"50\" src=\"/images/pic/ppp1.jpg\"/></td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">是</td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">下架</td>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"pn-opt\">查看</a> | <a href=\"#\" class=\"pn-opt\">修改</a> | <a href=\"#\" onclick=\"if(!confirm('您确定删除吗？')) {return false;}\" class=\"pn-opt\">删除</a> | <a href=\"../sku/list.jsp\" class=\"pn-opt\">库存</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"#ffffff\" onmouseover=\"this.bgColor='#eeeeee'\" onmouseout=\"this.bgColor='#ffffff'\">\r\n");
      out.write("\t\t\t<td><input type=\"checkbox\" name=\"ids\" value=\"73\"/></td>\r\n");
      out.write("\t\t\t<td>20141028114409502</td>\r\n");
      out.write("\t\t\t<td align=\"center\">依琦莲2014瑜伽服套装新款 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><img width=\"50\" height=\"50\" src=\"/images/pic/ppp2.jpg\"/></td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">是</td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">下架</td>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"pn-opt\">查看</a> | <a href=\"#\" class=\"pn-opt\">修改</a> | <a href=\"#\" onclick=\"if(!confirm('您确定删除吗？')) {return false;}\" class=\"pn-opt\">删除</a> | <a href=\"../sku/list.jsp\" class=\"pn-opt\">库存</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"#ffffff\" onmouseover=\"this.bgColor='#eeeeee'\" onmouseout=\"this.bgColor='#ffffff'\">\r\n");
      out.write("\t\t\t<td><input type=\"checkbox\" name=\"ids\" value=\"73\"/></td>\r\n");
      out.write("\t\t\t<td>20141028114407438</td>\r\n");
      out.write("\t\t\t<td align=\"center\">依琦莲2014瑜伽服套装新款 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><img width=\"50\" height=\"50\" src=\"/images/pic/ppp3.jpg\"/></td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">是</td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">下架</td>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"pn-opt\">查看</a> | <a href=\"#\" class=\"pn-opt\">修改</a> | <a href=\"#\" onclick=\"if(!confirm('您确定删除吗？')) {return false;}\" class=\"pn-opt\">删除</a> | <a href=\"../sku/list.jsp\" class=\"pn-opt\">库存</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr bgcolor=\"#ffffff\" onmouseover=\"this.bgColor='#eeeeee'\" onmouseout=\"this.bgColor='#ffffff'\">\r\n");
      out.write("\t\t\t<td><input type=\"checkbox\" name=\"ids\" value=\"73\"/></td>\r\n");
      out.write("\t\t\t<td>20141028114405217</td>\r\n");
      out.write("\t\t\t<td align=\"center\">依琦莲2014瑜伽服套装新款 瑜珈健身服三件套 广场舞蹈服装 女瑜伽服送胸垫 长袖紫色</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><img width=\"50\" height=\"50\" src=\"/images/pic/ppp4.jpg\"/></td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">是</td>\r\n");
      out.write("\t\t\t<td align=\"center\">否</td>\r\n");
      out.write("\t\t\t<td align=\"center\">下架</td>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"pn-opt\">查看</a> | <a href=\"#\" class=\"pn-opt\">修改</a> | <a href=\"#\" onclick=\"if(!confirm('您确定删除吗？')) {return false;}\" class=\"pn-opt\">删除</a> | <a href=\"../sku/list.jsp\" class=\"pn-opt\">库存</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<div class=\"page pb15\">\r\n");
      out.write("\t<span class=\"r inb_a page_b\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<font size=\"2\">首页</font>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<font size=\"2\">上一页</font>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<strong>1</strong>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"/product/list.do?&amp;isShow=0&amp;pageNo=2\">2</a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"/product/list.do?&amp;isShow=0&amp;pageNo=3\">3</a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"/product/list.do?&amp;isShow=0&amp;pageNo=4\">4</a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"/product/list.do?&amp;isShow=0&amp;pageNo=5\">5</a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"/product/list.do?&amp;isShow=0&amp;pageNo=2\"><font size=\"2\">下一页</font></a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"/product/list.do?&amp;isShow=0&amp;pageNo=5\"><font size=\"2\">尾页</font></a>\r\n");
      out.write("\t\r\n");
      out.write("\t\t共<var>5</var>页 到第<input type=\"text\" size=\"3\" id=\"PAGENO\"/>页 <input type=\"button\" onclick=\"javascript:window.location.href = '/product/list.do?&amp;isShow=0&amp;pageNo=' + $('#PAGENO').val() \" value=\"确定\" class=\"hand btn60x20\" id=\"skip\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t</span>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"margin-top:15px;\"><input class=\"del-button\" type=\"button\" value=\"删除\" onclick=\"optDelete();\"/><input class=\"add\" type=\"button\" value=\"上架\" onclick=\"isShow();\"/><input class=\"del-button\" type=\"button\" value=\"下架\" onclick=\"isHide();\"/></div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
